name: "Workflow Status Action"
description: "Trigger events like notifications or alerts using the workflow status"
author: "David Boenig <martialonline>"

inputs:
  token:
    description: "The GITHUB_TOKEN secret"
    required: false
    default: ""

outputs:
  status:
    description: "Returns either success or failed as workflow status"
    value: ${{ steps.workflow-status.outputs.status }}
runs:
  using: "composite"
  steps:
    - id: workflow-status
      run: |
        url="${GITHUB_API_URL}/repos"
        repo="${GITHUB_REPOSITORY}"
        run_id="${GITHUB_RUN_ID}"

        if [[ -z "${{ inputs.token }}" ]]; then 
          PARAMS=(-s -H "content-type: application/json")
        else
          PARAMS=(-s -H "content-type: application/json" -H "authorization: Bearer ${{ inputs.token }}")
        fi

        failure=$(curl "${PARAMS[@]}" "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "failure").conclusion' | \
        wc -l)

        cancelled=$(curl "${PARAMS[@]}" "${url}/${repo}/actions/runs/${run_id}/jobs" | \
        jq -r '.jobs[] | select(.status == "completed" and .conclusion == "cancelled").conclusion' | \
        wc -l)

        if [ "${failure}" -gt 0 ]; then
          status="failure"
        elif [ "${cancelled}" -gt 0 ]; then
          status="cancelled"
        else 
          status="success"
        fi

        echo "::set-output name=status::${status}"
      shell: bash
branding:
  icon: check-square
  color: gray-dark
